-- core settings
require("plugins-setup")
require("colorscheme")
require("keymaps")
require("options")

-- addtitional plugins
require("plugins.autopairs")
require("plugins.bufferline")
require("plugins.comment")
require("plugins.gitsigns")
require("plugins.lsp.lspconfig")
require("plugins.lsp.lspsaga")
require("plugins.lsp.mason")
require("plugins.lsp.null-ls")
require("plugins.lualine")
require("plugins.nvim-cmp")
require("plugins.nvim-tree")
require("plugins.telescope")
require("plugins.toggleterm")
require("plugins.treesitter")
